name: Rust

on:
  push:
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo +nightly fmt --all --check

      - name: Run cargo clippy
        run: cargo +nightly clippy --all-targets
        env:
          PWD: ${{ github.workspace }} # without it ci can't see env!("PWD") 

  cross-testing:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Capture the Rust compiler version to include in the cache key
      - name: Get rustc version
        id: rustc-version
        run: echo "rustc_version=$(rustc --version)" >> $GITHUB_OUTPUT

      # Restore cached dependencies and build artifacts
      - name: Cache Rust artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/       # Cache both debug and release build artifacts
          # Unique cache key based on OS, Rust compiler version, and important files
          key: ${{ runner.os }}-rustc-${{ steps.rustc-version.outputs.rustc_version }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', '**/*.rs', 'contrib/test_features.sh') }}

      # Build the project binaries
      - name: Build Project Binaries
        run: cargo build --bins --verbose

      # Run the feature testing script
      - name: Run feature tests
        run: ./contrib/test_features.sh
        shell: bash

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}

      - name: Build Docker image
        run: |
          docker buildx build --cache-to=type=local,dest=/tmp/.buildx-cache --cache-from=type=local,src=/tmp/.buildx-cache -t dlsz/floresta:latest .
